### ISSUE TITLE
No ToS and Privacy Policy

### ISSUE THREAD

**Issue by vsly-ru** [february-labs/devgpt-releases#52]
After I downloaded the app, I wanted to create an account, but the links to Terms of Service and Privacy Policy are both linked to a [page that does not exist](https://www.devgpt.com/privacy-policy) (and the same one). 

For me the privacy of my code is **crucial**(I signed an NDA after all) and this aspect is not clearly mentioned anywhere on the site. So I expected at least to find out about it while reading the Privacy Policy. But it doesn't even exist. For me it's a blocker – **I can't use your product**.

**Comment by maxwell-01** [comment]
Came here looking for answers to this too

**Comment by tom-lewis-code** [comment]
hey @maxwell-01 @vsly-ru! Sorry I can't get the @'s of other people that have reacted to this post!

We do have an IP policy, the link in app is just misconfigured. Policy can be found here: https://www.devgpt.com/ip-policy. Will have this fixed for our newest release, hugely sorry about this messup.

**Comment by maxwell-01** [comment]
Thanks Tom! I found this and did take a quick read through. Apologies if I've missed it but its not clear whether you run the model in your own environment or whether you send the data to OpenAI via their API. Please could you clarify for me?

**Comment by johnredberg** [comment]
Hi @tom-lewis-code , 

I'm quite sorry to be super blunt here but... **who** is devgpt? **Who** is "February Labs"? Or is it "Feb Labs"?

- There's no legal information on your website. Did you know that UK law requires that you publish your company name, registration ID, address, contact information, ...?
- I can't find any active company in the UK registry by that name.
- Where (in the world) is user data stored?
- Are your data centers, third-party providers, business processes ISO certified? Do you have a compliance and due diligence officer?
- Yes, there is an "IP Policy", but what is that...? 
    - You encrypt data at rest, but only "essential personnel" of your giant 4 person operation has access to that? So it's not end-to-end encrypted then? So, great if your data center gets compromised, but not so great if one of your employees goes rogue?
    - "any code or output generated by DevGPT *during the trial period* is the sole property of your organization" [emphasis mine] is mine. What about paying subscribers?
    - "Rest assured that February Labs is *committed to upholding* the highest standards" [emphasis mine] I mean, that says nothing. "I promise to be a good boy." And again, who is "February Labs"?
    - **Has any (competent) lawyer ever even read this?**
- DevGPT's LinkedIn About page says you're based in the north of the UK, but your headquarters are in "London, UK". a) not very specific, b) last time I checked, it's still quite a drive from London to the Scottish border.
- Your LInkedIn (Tom) lists feb co uk as your personal homepage. So, is this some hobby of yours? "Why not give it a shot?" type of thing?
- Why join you? Well, according to your homepage, the answer is "Aliquam et tellus urna". 
- Who's the team? Obviously "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

I wouldn't mind or would never criticize anybody so harshly for a personal project, motivated team of friends, or an ambitions startup on GitHub. But...  I found you through a sponsored ad on Fireship... I'm quite surprised Jeff took you on. Maybe he's really starting to outsource some of his work to an AI clone of himself...

You want to give it a shot in the big league? Then do your homework, and do it well.

You guys might have the best of intentions and be the most honest and ethical people in the world. But everything about your product and your "company" screams "AI FOMO fake it till you make it". For me personally, this immediately means zero trust in your project. Forever. Period. 

But I don't know, maybe I'm just too cautious compared to each of the "tens of thousands of engineers" who are definitely using your platform.

All the best,

J

**Comment by tom-lewis-code** [comment]
hey @beminee @johnredberg @vsly-ru @maxwell-01,

I appreciate all of your concern here, completely a valid topic to be concerned about, this is a very important step for our team to get right. One of the less nice points about being a small team is things can be forgotten to be updated. As you can imagine, we have no intention to mislead or do harm; but it's time to make that obvious from the outside.

To clarify the main point, we do not access or store your repo. Code generated by the AI is isolated and stored securely. The word trial in the ip-policy here is incorrect, and we'll change that as a priority. Our third-party provider for database is SOC2 compliant. Our app is now open source, but perhaps we would benefit from open-sourcing our landing pages too.

We’ll update the privacy policy and website to show our registered company name and company number. 

We have been trading since February 2020 and are funded. The same goes for all of the above company information not being easily findable, we will amend this.

@johnredberg Our testing / mods team could hugely benefit from your knowledge. We have a Discord open for the community if that's your type of thing. I'm not sure where you found Lorem, but I'd love to get that replaced! I can assure you this is more than a hobby at this point.

@maxwell-01 We don't use our own LLM, prompts are processed via OpenAI.

Thank you all for your reports, I appreciate all of your feedback as we continue to improve. **This conversation will be converted into tickets, and each point dealt with that we need to change.** If I missed anything, do let me know.
